import { createHash } from 'node:crypto'
import { appendFile, mkdir, rename, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const CACHE_HASH_URL = 'https://www.haxball.com/cache_hash.json'
const OUTPUT_PATH = resolve('src/generated/headless.ts')

export interface HeadlessSourceMetadata {
	cacheHash: string
	sourceHash: string
	sha256: string
}

function countMatches(source: string, pattern: RegExp): number {
	return [...source.matchAll(pattern)].length
}

export function inspectHeadlessSource(
	cacheHash: string,
	source: string,
): HeadlessSourceMetadata {
	if (!/^[A-Za-z0-9_-]+$/.test(cacheHash)) {
		throw new Error(`Unexpected Haxball cache hash: ${cacheHash}`)
	}

	const sourceHash = source.match(/\/\*[\s\S]*?\b([a-f0-9]{8})\b/)?.[1]
	if (!sourceHash) {
		throw new Error('Failed to extract the Haxball source hash')
	}

	const invariants: Array<[string, RegExp, number]> = [
		['HBInit assignment', /window\.parent\.HBInit\s*=/g, 1],
		['WebSocket construction', /new WebSocket\(/g, 1],
		['room link element', /getElementById\("roomlink"\)/g, 1],
		['reCAPTCHA element', /getElementById\("recaptcha"\)/g, 1],
	]

	for (const [name, pattern, expected] of invariants) {
		const actual = countMatches(source, pattern)
		if (actual !== expected) {
			throw new Error(
				`Expected ${expected} ${name} occurrence, found ${actual}`,
			)
		}
	}

	return {
		cacheHash,
		sourceHash,
		sha256: createHash('sha256').update(source).digest('hex'),
	}
}

export function createGeneratedModule(
	metadata: HeadlessSourceMetadata,
	source: string,
): string {
	const header = `// Generated by scripts/update-headless.ts. Do not edit manually.
// @ts-nocheck
import type { HeadlessEnvironment } from '../runtime.ts'
import type { HBInit } from '../types.ts'

export const HAXBALL_CACHE_HASH = ${JSON.stringify(metadata.cacheHash)}
export const HAXBALL_SOURCE_HASH = ${JSON.stringify(metadata.sourceHash)}
export const HAXBALL_SOURCE_SHA256 = ${JSON.stringify(metadata.sha256)}

export function loadHeadless(
	environment: HeadlessEnvironment,
): Promise<typeof HBInit> {
	return new Promise((resolve, reject) => {
		const {
			WebSocket,
			XMLHttpRequest,
			JSON5,
			pako,
			RTCPeerConnection,
			RTCIceCandidate,
			RTCSessionDescription,
			crypto,
			performance,
			TextEncoder,
		} = environment
		const window = environment.createWindow(resolve)

		try {
`

	const footer = `
		} catch (error) {
			reject(error)
		}
	})
}
`

	return `${header}${source.trim()}${footer}`
}

export async function updateHeadless(): Promise<HeadlessSourceMetadata> {
	const cacheResponse = await fetch(CACHE_HASH_URL)
	if (!cacheResponse.ok) {
		throw new Error(
			`Failed to fetch cache hash: ${cacheResponse.status} ${cacheResponse.statusText}`,
		)
	}

	const cacheHash: unknown = await cacheResponse.json()
	if (typeof cacheHash !== 'string') {
		throw new Error('Haxball cache hash response is not a string')
	}

	const sourceUrl = `https://www.haxball.com/${cacheHash}/__cache_static__/g/headless-min.js`
	const sourceResponse = await fetch(sourceUrl)
	if (!sourceResponse.ok) {
		throw new Error(
			`Failed to fetch headless source: ${sourceResponse.status} ${sourceResponse.statusText}`,
		)
	}

	const source = await sourceResponse.text()
	if (!source) throw new Error('Haxball headless source is empty')

	const metadata = inspectHeadlessSource(cacheHash, source)
	const output = createGeneratedModule(metadata, source)
	const temporaryPath = `${OUTPUT_PATH}.tmp`

	await mkdir(dirname(OUTPUT_PATH), { recursive: true })
	await writeFile(temporaryPath, output, 'utf8')
	await rename(temporaryPath, OUTPUT_PATH)

	if (process.env.GITHUB_OUTPUT) {
		await appendFile(
			process.env.GITHUB_OUTPUT,
			`new_hash=${metadata.sourceHash}\n`,
			'utf8',
		)
	}

	console.log(`SUCCESS:${metadata.sourceHash}`)
	return metadata
}

const entryPath = process.argv[1]
if (entryPath && import.meta.url === pathToFileURL(resolve(entryPath)).href) {
	await updateHeadless()
}
